CREATE TABLE borrowings (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, created_at TIMESTAMP, returned_at TIMESTAMP, current BOOLEAN DEFAULT 't', user_id INTEGER NOT NULL, item_id INTEGER NOT NULL);

CREATE TABLE communities (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50), state VARCHAR(50), zip INTEGER, description TEXT, created_on DATE);

CREATE TABLE helpfuls (helpful BOOLEAN, review_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(review_id, user_id));

CREATE TABLE issues (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, created_at TIMESTAMP, resolved BOOLEAN DEFAULT 'f', admin_notified BOOLEAN DEFAULT 'f', borrowing_id INTEGER NOT NULL);

CREATE TABLE item_tags (item_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY(item_id, tag_id));

CREATE TABLE items (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, value DECIMAL(6, 2), created_at TIMESTAMP, max_loan INTEGER, name VARCHAR(50), desc TEXT, image VARCHAR(50), user_id INTEGER NOT NULL);

CREATE TABLE karmas (from INTEGER NOT NULL, unto INTEGER NOT NULL, type BOOLEAN, PRIMARY KEY(from, unto));

CREATE TABLE messages (message_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, body TEXT, created_at TIMESTAMP, sender INTEGER, receiver INTEGER);

CREATE TABLE parties (issue_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(issue_id, user_id));

CREATE TABLE reviews (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, body TEXT, created_at TIMESTAMP, user_id INTEGER NOT NULL, item_id INTEGER NOT NULL);

CREATE TABLE tags (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50));
CREATE TABLE users (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50), address VARCHAR(50), city VARCHAR(50), state VARCHAR(50), zip VARCHAR(50), location_id INTEGER, email VARCHAR(50), created_at TIMESTAMP, password_hash VARCHAR(60), is_admin BOOLEAN, community_id INTEGER);
CREATE TABLE zip_codes (id INTEGER PRIMARY KEY AUTO_INCREMENT, zip INTEGER, city_name VARCHAR(50), latitude DECIMAL, longitude DECIMAL);
